spring.application.name=hw-16-artemis
spring.jms.listener.min-concurrency=1
server.port=8081
spring.artemis.broker-url=tcp://localhost:61616
spring.artemis.user=artemis
spring.artemis.password=artemis






